### ISSUE TITLE
Ability to port-forward to runtime service

### ISSUE THREAD

**Issue by shuaibiyy** [curityio/idsvr-helm#16]
It can be helpful to be able to port-forward to the runtime service. Currently, the runtime service selectors match both runtime and admin pods. Since admin pods don't have a http port, attempting to port-forward results in an error:
```
> kubectl port-forward service/curity-idsvr-runtime-svc 9000:80
error: Pod 'curity-idsvr-admin-pod' does not have a named port 'http-port'
```
One solution is to add a selector and matching label to the service and deployment respectively like in this [commit](https://github.com/shuaibiyy/idsvr-helm/commit/73d1cde74a5dde28852a715f8b1ef20b17d71530).

**Comment by anestos** [comment]
Please make a PR that would be accepted ;)
