### ISSUE TITLE
curity.config.uiEnabled not effective

### ISSUE THREAD

**Issue by ju-cu** [curityio/idsvr-helm#29]
The default value for `curity.config.uiEnabled` is `false` and thus AdminUI and RESTConf interface should be disabled by default. However, the parameter only prevents the admin-port to be added to list of ports in the deployment template. Ports listed there are just informative. See https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#ports for reference. Port-forwarding will work nevertheless. I expect this parameter to disable the installation of the adminUI, i.e. run `unattendinstall --without-admin-ui`

**Comment by anestos** [comment]
I kinda aggree with this @ju-cu , but the rational behind how this works is that when you have the ui disabled, you are adding configuration some other way (i.e with a secret, configMap or by using another image that contains configuration). 
When that is the case, the unattendedinstall should not even run, so having this extra flag added seemed unnecessary

**Comment by ju-cu** [comment]
Thanks @anestos for clarifying. The description of the parameter in the chart readme does not indicate that this parameter is supposed to be used together with a configuration that does not include the admin UI. I believe a better name for the parameter would then be `curity.config.exposeUiPort` or similar that is more self-explanatory for what it does.
