### ISSUE TITLE
Add option to allow HTTP connections.

### ISSUE THREAD

**Issue by Xachman** [curityio/idsvr-helm#5]
In some cases another service will be terminating TLS.  It would be nice if during the initial install we could have an option to allow HTTP connections.

**Comment by travisspencer** [comment]
For the admin node, that is. Sure. No problem. We'll add this.

**Comment by Xachman** [comment]
Thanks yes for the admin node.

**Comment by anestos** [comment]
Curity version 6.0.0 will allow for this to be controlled by an environment variable. 
I ll make a PR with this feature included that will only work when 6.0.0 is out.
