### ISSUE TITLE
unmarshal errors while trying to add the curity helm repo

### ISSUE THREAD

**Issue by avapaX** [curityio/idsvr-helm#65]
Hi, I'm trying to add the curity helm repo so that I can use the charts. When doing so, I get this error:

```console
Error: looks like "https://curityio.github.io/idsvr-helm" is not a valid chart repository or cannot be reached: error converting YAML to JSON: yaml: unmarshal errors:
  line 23: key "apiVersion" already set in map
  line 25: key "entries" already set in map
```

When I search for the repo using 
```console
helm search hub curity
```
 the chart version is still listed as 0.12.2 and the app version as 8.1.1

**Comment by anestos** [comment]
Thank you for reporting, there was a typo introduced with the latest release on Friday. We have now fixed it.
