### ISSUE TITLE
Improve Backup process 

### ISSUE THREAD

**Issue by bondarau** [curityio/idsvr-helm#72]
We need the ability to modify the backup process and additionally copy the configuration after each change to AWS S3 Bucket. What if I prepare a pull request and move the backup script(data) to a values file, so we can take the value from the values file? This way, everyone can customize backup process it as needed.

**Comment by anestos** [comment]
I would suggest to do that in the Docker Image, if you build a custom one anyway for plugins/templates etc it should be trivial to add a file in the post-commit-scripts directory. If you don't create your own image, we could look into this a bit more  but it needs to be handled with care. Adding "work" in the post-commit-scripts can break the admin UI, if this work takes a meaningful amount of time (i believe more than 10 or 15 seconds). I already want to update the existing backup file to be async to avoid this so maybe i can also add custom scripts from a configurable config map too if that's necessary for you

**Comment by bondarau** [comment]
https://github.com/curityio/idsvr-helm/pull/74

**Comment by bondarau** [comment]
https://github.com/curityio/idsvr-helm/tree/idsvr-0.12.14
