### ISSUE TITLE
Expose log4j.xml to be able to change appender layout to JSONLayout

### ISSUE THREAD

**Issue by slivkamiro** [curityio/idsvr-helm#85]
I would like to change the log format to json as suggested by following articles:

https://curity.io/resources/learn/log-to-elasticsearch/#deploy-the-curity-identity-server
https://curity.io/resources/learn/logging-best-practices/#log-formats

is there a way to do that using this helm chart?

**Comment by anestos** [comment]
You can use 
`curity.admin.extraVolumeMounts` - `curity.admin.extraVolumes` and 
`curity.runtime.extraVolumeMounts` - `curity.runtime.extraVolumes` and 
 to mount a different log4j2.xml file in `/opt/idsvr/etc/log4j2.xml`
